### ISSUE TITLE
When i type npm start

### ISSUE THREAD

**Issue by novalmaulana050** [out386/aria-telegram-mirror-bot#73] opened 2020-02-01 18:25 UTC
> mirror-bot@2.0.0 start C:\Windows\System32\aria-telegram-mirror-bot
> NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

'NTBA_FIX_319' not recognized as an internal or external command, operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirror-bot@2.0.0 start: 'NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js'
npm ERR! Exit status 1
npm ERR! failed at the mirror-bot@2.0.0 start script
npm ERR! this is probably not a problem with npm. There is likely additional logging above output above

npm ERR! A complete log of this run can be found in:
npm ERR!   C:\Users\plt\Appdata\Roaming\npm-cache\_logs\2020-02-01T18_24_18_01_8Z-debug.log

How to solve it?

**Comment by out386** [comment] 2020-02-01 18:43
Duplicate of #56

**Closed by out386** 2020-02-01 18:43 UTC
